### PR TITLE
Fix #267: improvements to Terms (T&C)

### LINKED ISSUE #267: Improve Terms (T&C) based on feedback
Change the terms to contain the feedback fixes from @trentmc provided [here](https://github.com/oceanprotocol/pdr-private/issues/42)

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #267.

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
Right it's a little bit annoying but I think still readable. We shouldn't close the model until user press the continue button.
If you think it's not readable I could just link to Github readme file, but I thought user might feel better to not be interrupted on the action, but I also considered that as an option.

**Comment by KatunaNorbert** [comment]
We could, but then it would not be suggestive for the user what happened with the modal and how can they open it again

**Comment by KatunaNorbert** [comment]
I disabled the modal from the terms page, but when clocking on terms link instead of closing the modal on current tab it opens a new tab with terms there the modal is closed. Then user can come close that after he read it and come back to modal and click on continue. This way we don't really break the main flow.

**Comment by kdetry** [comment]
If we use the "cherry-pick" command to take changes from other commits for the next time, it wouldn't cause conflicts. LGTM

**Review by kdetry — APPROVED** [review]

**Pull request merged**
