### PR TITLE
issue151 : Mobile Version

### LINKED ISSUE #151: Quick wins towards making app mobile friendly
There could be some easy wins that we could do by looking into how we can make the app mobile friendly.
Explore the possibilities and make app manageable on the mobile and smaller devices. 

This issue is _not_ about making the app super useful on mobile. More just for people to check out as a first cut.

### DoD
- [ ] Setup scrolling based on media type. Avoid showing horizontal/scroll bars when not needed.

### PR DESCRIPTION
**Pull request by kdetry**
Fixes #151 

Changes proposed in this PR:

- [x] Mobile version of the table
- [x] Mobile version of the menu and header

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
The burger menu icon is visible on large screens as well, it should be hidden

Screenshot 2023-10-26 at 10 30 52

**Comment by KatunaNorbert** [comment]
I suggest we set the default scroll offset to show the following columns:
Screenshot 2023-10-26 at 16 36 33

This way user sees right away most important values: predictions and accuracy without have to scroll.
I also noticed while looking at Posthog that there are users who doesn't know they can scroll the table horizontally, so they don't even see the prediction column.

**Comment by idiom-bytes** [comment]
I'm seeing the same issue that @KatunaNorbert reported @kdetry 
image

**Comment by idiom-bytes** [comment]
> I suggest we set the default scroll offset to show the following columns...

Not sure how I feel about it. I kind of agree, trent might have some opinions on this.

**Comment by KatunaNorbert** [comment]
pushed some small UI improvements so the top part looks a little bit better structured
Screenshot 2023-11-09 at 16 20 45

**Review by KatunaNorbert — APPROVED** [review]
LGTM!

**Pull request merged**
