### PR TITLE
issue-175

### LINKED ISSUE #175: Create switch between dark and light mode
- [x] Add a component that enables user to switch between light and dark mode
- [x] Save user option inside local storage
- [x] Offer light mode as default

### PR DESCRIPTION
**Pull request by kdetry**
Fixes #175 

Changes proposed in this PR:
- Add a component that enables user to switch between light and dark mode
- Save user option inside local storage
- Offer light mode as default

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
It is not working for me, whatever I chose only dark more is displayed, which is my machines setting
Screenshot 2023-10-13 at 14 33 28

**Comment by kdetry** [comment]
Let me inspect

**Comment by kdetry** [comment]
Fixed and the code quality is improved 👍

**Comment by kdetry** [comment]
> Could you make it light by default without taking in consideration the machine configuration? Our purpose is to market and show the light mode first.

done

**Review by KatunaNorbert — APPROVED** [review]

**Pull request merged**
