### PR TITLE
PriceDeltaIssue

### LINKED ISSUE #227: Price directions are not working correctly on the table
Price directions are not working correctly on the table.

DoD
- [ ] solve the problem which causes at the loading state of the price component

### PR DESCRIPTION
**Pull request by kdetry**
Fixes #227 
Price direction issue and refactoring on the EpochDisplay component

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
Current price delta seems to be alright, but I see some issues with the direction of the history price delta. In some cases the price is the same, but there is still a movement of up or down displayed.
Screenshot 2023-09-25 at 10 27 06

**Comment by KatunaNorbert** [comment]
I see the issue now. We are displaying the close price for the candles, but when we are calculating the delta, instead of using the close price of previous candle which is displayed, the open price of the current candle it's used, which in some cases is different.
Check logs from bellow for example where the objects are the candles and then on lines 131: startPrice, endPrice, delta, epoch
Screenshot 2023-09-26 at 10 35 33




We need to be consistent here and display what we use in calculation, otherwise there it's going to be conflicts.
Looking at trueval from pdr-backend It seems they are using the open price of 2 candles: https://github.com/oceanprotocol/pdr-backend/blob/main/pdr_backend/trueval/trueval_agent_base.py#L115C4-L115C4

**Comment by KatunaNorbert** [comment]
Based on slack discussion we should stick with close price of epoch i - close price of epoch i-1 for delta value calculation

**Review by KatunaNorbert — APPROVED** [review]

**Comment by kdetry** [comment]
@KatunaNorbert Have you check by using the data which is on the finance website ?

**Comment by KatunaNorbert** [comment]
@kdetry yes, feel free to double check. Look at 5m candles close prices.

**Comment by kdetry** [comment]
I checked it too, it looks consistent

**Pull request merged**
